# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ESP_Module.ui'
#
# Created: Thu Jun 30 13:41:19 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(753, 681)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/AIbEiAIAAABECP2Iptyl4PzmnAEiC3ZjYXJkX3Bob3RvKihiMjczYWVlNWQ1ZWVlNjYyY2U2NzA5YWUwNzgzMjE2MmZkMGYxN2Q5MAFyoVXTDsx0nC3OGfmWE7vsTYpe9Q.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/background/Icons/background.jpg);background-repeat: repeat;}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QTabWidget{background-color:blue;}\n"
"\n"
"QWidget#scrollArea{background-color: blue;}\n"
"QWidget#page_3{background:transparent;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Selection_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Selection_pushButton.sizePolicy().hasHeightForWidth())
        self.Selection_pushButton.setSizePolicy(sizePolicy)
        self.Selection_pushButton.setMinimumSize(QtCore.QSize(130, 30))
        self.Selection_pushButton.setObjectName(_fromUtf8("Selection_pushButton"))
        self.gridLayout_2.addWidget(self.Selection_pushButton, 0, 3, 1, 1)
        self.ConnectionStatus = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectionStatus.sizePolicy().hasHeightForWidth())
        self.ConnectionStatus.setSizePolicy(sizePolicy)
        self.ConnectionStatus.setMinimumSize(QtCore.QSize(100, 30))
        self.ConnectionStatus.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);"))
        self.ConnectionStatus.setObjectName(_fromUtf8("ConnectionStatus"))
        self.gridLayout_2.addWidget(self.ConnectionStatus, 0, 4, 1, 1)
        self.SaveLog = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveLog.sizePolicy().hasHeightForWidth())
        self.SaveLog.setSizePolicy(sizePolicy)
        self.SaveLog.setMinimumSize(QtCore.QSize(110, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/Notepad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveLog.setIcon(icon1)
        self.SaveLog.setIconSize(QtCore.QSize(32, 32))
        self.SaveLog.setObjectName(_fromUtf8("SaveLog"))
        self.gridLayout_2.addWidget(self.SaveLog, 4, 3, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.ClearLog = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearLog.sizePolicy().hasHeightForWidth())
        self.ClearLog.setSizePolicy(sizePolicy)
        self.ClearLog.setMinimumSize(QtCore.QSize(100, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearLog.setIcon(icon2)
        self.ClearLog.setIconSize(QtCore.QSize(32, 32))
        self.ClearLog.setObjectName(_fromUtf8("ClearLog"))
        self.gridLayout_2.addWidget(self.ClearLog, 4, 4, 1, 1)
        self.SerialConsole = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SerialConsole.sizePolicy().hasHeightForWidth())
        self.SerialConsole.setSizePolicy(sizePolicy)
        self.SerialConsole.setMinimumSize(QtCore.QSize(600, 100))
        self.SerialConsole.setMouseTracking(True)
        self.SerialConsole.setReadOnly(True)
        self.SerialConsole.setObjectName(_fromUtf8("SerialConsole"))
        self.gridLayout_2.addWidget(self.SerialConsole, 7, 0, 1, 5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.CloseServer = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseServer.sizePolicy().hasHeightForWidth())
        self.CloseServer.setSizePolicy(sizePolicy)
        self.CloseServer.setMinimumSize(QtCore.QSize(0, 250))
        self.CloseServer.setAutoFillBackground(False)
        self.CloseServer.setStyleSheet(_fromUtf8("QMainWindow{background-image: url(:/background/Icons/background.jpg);}\n"
"\n"
"QToolBar{background:blue;}\n"
"\n"
"QWidget::tabWidget{background-color: blue;}\n"
"QTabBar::tab { background: darkblue; color: white; padding: 10px; border: 2px solid blue;}\n"
"QTabBar::tab:selected {background: rgb(217, 217, 0);  color: black; }\n"
"QTabBar::tab:!selected {background:darkblue;  color: white;}\n"
"/*QTabBar {background-color: blue;} */\n"
"QTabBar::tab:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"\n"
"QPushButton{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\";}\n"
"QPushButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton:pressed{background-color: lightblue;}\n"
"QPushButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QPushButton#connectButton{ background-color: darkred;}\n"
"QPushButton#connectButton:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QPushButton#connectButton:pressed{background-color: lightblue;}\n"
"QPushButton#connectButton:disabled{background-color: rgb(176, 176, 176);}\n"
"\n"
"QComboBox{border-style:solid;background-color:darkblue;color:white;border-radius:3px;font: 12pt \"MS Shell Dlg 2\"; padding: 10px}\n"
"QComboBox:hover{color:#ccc;    background-color: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.517, y2:1, stop:0 rgba(45, 45, 45, 255), stop:0.505682 rgba(45, 45, 45, 255), stop:1 rgba(29, 29, 29, 255));    border-color:#2d89ef;border-width:2px;}\n"
"QComboBox:pressed{background-color: lightblue;}\n"
"\n"
"QLineEdit {border:4px outset; border-radius: 8px; border-color: blue; color:rgb(0, 0, 0);  background-color: rgb(235, 235, 235); padding:10px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"/*QLineEdit { border-radius: 8px;  color:black;background-color: white; } */\n"
"QLineEdit:focus {  border:4px outset; border-radius: 8px; border-color: rgb(41, 237, 215); color:rgb(0, 0, 0);  background-color: rgb(240, 204, 204); }\n"
"\n"
"QLabel {border:4px outset; border-radius: 0px; border-color: blue; color:white;  background-color: darkblue; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}\n"
"QPlainTextEdit {border:4px outset; border-radius: 0px; border-color: blue; color:black;  background-color: rgb(235, 235, 235);; padding:5px;font: 75 12pt \"MS Shell Dlg 2\";}"))
        self.CloseServer.setDocumentMode(True)
        self.CloseServer.setTabsClosable(False)
        self.CloseServer.setObjectName(_fromUtf8("CloseServer"))
        self.Settings = QtGui.QWidget()
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.gridLayout_8 = QtGui.QGridLayout(self.Settings)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 2, 1, 1)
        self.connectButton = QtGui.QPushButton(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(200, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon3)
        self.connectButton.setIconSize(QtCore.QSize(32, 32))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout_8.addWidget(self.connectButton, 3, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 4, 1, 1, 1)
        self.baudcomboBox = QtGui.QComboBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudcomboBox.sizePolicy().hasHeightForWidth())
        self.baudcomboBox.setSizePolicy(sizePolicy)
        self.baudcomboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.baudcomboBox.setObjectName(_fromUtf8("baudcomboBox"))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.baudcomboBox.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.baudcomboBox, 3, 1, 1, 1)
        self.findButton = QtGui.QPushButton(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findButton.sizePolicy().hasHeightForWidth())
        self.findButton.setSizePolicy(sizePolicy)
        self.findButton.setMinimumSize(QtCore.QSize(200, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findButton.setIcon(icon4)
        self.findButton.setIconSize(QtCore.QSize(32, 32))
        self.findButton.setObjectName(_fromUtf8("findButton"))
        self.gridLayout_8.addWidget(self.findButton, 1, 3, 1, 1)
        self.portComboBox = QtGui.QComboBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setMinimumSize(QtCore.QSize(200, 50))
        self.portComboBox.setObjectName(_fromUtf8("portComboBox"))
        self.gridLayout_8.addWidget(self.portComboBox, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 2, 1, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/setting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseServer.addTab(self.Settings, icon5, _fromUtf8(""))
        self.wireless = QtGui.QWidget()
        self.wireless.setObjectName(_fromUtf8("wireless"))
        self.gridLayout_9 = QtGui.QGridLayout(self.wireless)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.scrollArea_2 = QtGui.QScrollArea(self.wireless)
        self.scrollArea_2.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 698, 410))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem7, 5, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem8, 2, 6, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem9, 17, 3, 1, 1)
        self.Wifi_Search = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wifi_Search.sizePolicy().hasHeightForWidth())
        self.Wifi_Search.setSizePolicy(sizePolicy)
        self.Wifi_Search.setMinimumSize(QtCore.QSize(150, 50))
        self.Wifi_Search.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/wifi_Logo-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wifi_Search.setIcon(icon6)
        self.Wifi_Search.setIconSize(QtCore.QSize(50, 50))
        self.Wifi_Search.setObjectName(_fromUtf8("Wifi_Search"))
        self.gridLayout_10.addWidget(self.Wifi_Search, 4, 6, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem10, 0, 3, 1, 1)
        self.WirelessSelection = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.WirelessSelection.setObjectName(_fromUtf8("WirelessSelection"))
        self.WirelessSelection.addItem(_fromUtf8(""))
        self.WirelessSelection.addItem(_fromUtf8(""))
        self.WirelessSelection.addItem(_fromUtf8(""))
        self.WirelessSelection.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.WirelessSelection, 1, 6, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem11, 4, 7, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 4, 0, 1, 1)
        self.WifiCombobox = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.WifiCombobox.setObjectName(_fromUtf8("WifiCombobox"))
        self.WifiCombobox.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.WifiCombobox, 4, 4, 1, 1)
        self.wifi_pass = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.wifi_pass.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.wifi_pass.setInputMask(_fromUtf8(""))
        self.wifi_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.wifi_pass.setObjectName(_fromUtf8("wifi_pass"))
        self.gridLayout_10.addWidget(self.wifi_pass, 5, 4, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_10.addWidget(self.checkBox, 9, 4, 1, 1)
        self.Default_wifi = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Default_wifi.setObjectName(_fromUtf8("Default_wifi"))
        self.gridLayout_10.addWidget(self.Default_wifi, 11, 4, 1, 1)
        self.Refresh = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Refresh.sizePolicy().hasHeightForWidth())
        self.Refresh.setSizePolicy(sizePolicy)
        self.Refresh.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.Refresh.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh.setIcon(icon7)
        self.Refresh.setIconSize(QtCore.QSize(32, 32))
        self.Refresh.setObjectName(_fromUtf8("Refresh"))
        self.gridLayout_10.addWidget(self.Refresh, 2, 4, 1, 1)
        self.wifi_connect = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifi_connect.sizePolicy().hasHeightForWidth())
        self.wifi_connect.setSizePolicy(sizePolicy)
        self.wifi_connect.setMinimumSize(QtCore.QSize(150, 50))
        self.wifi_connect.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/connect-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wifi_connect.setIcon(icon8)
        self.wifi_connect.setIconSize(QtCore.QSize(32, 32))
        self.wifi_connect.setObjectName(_fromUtf8("wifi_connect"))
        self.gridLayout_10.addWidget(self.wifi_connect, 10, 4, 1, 1)
        self.Disconnect = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disconnect.sizePolicy().hasHeightForWidth())
        self.Disconnect.setSizePolicy(sizePolicy)
        self.Disconnect.setMinimumSize(QtCore.QSize(150, 50))
        self.Disconnect.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/45420.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Disconnect.setIcon(icon9)
        self.Disconnect.setIconSize(QtCore.QSize(32, 32))
        self.Disconnect.setObjectName(_fromUtf8("Disconnect"))
        self.gridLayout_10.addWidget(self.Disconnect, 10, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 1, 4, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem13, 4, 5, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea_2, 1, 1, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/Custom-Icon-Design-Mono-General-3-Wifi.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseServer.addTab(self.wireless, icon10, _fromUtf8(""))
        self.CommandMode = QtGui.QWidget()
        self.CommandMode.setObjectName(_fromUtf8("CommandMode"))
        self.gridLayout_7 = QtGui.QGridLayout(self.CommandMode)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ScriptLineEdit = QtGui.QLineEdit(self.CommandMode)
        self.ScriptLineEdit.setObjectName(_fromUtf8("ScriptLineEdit"))
        self.gridLayout_7.addWidget(self.ScriptLineEdit, 1, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 1, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 1, 4, 1, 1)
        self.SendButton = QtGui.QPushButton(self.CommandMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMinimumSize(QtCore.QSize(150, 50))
        self.SendButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/running_man.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SendButton.setIcon(icon11)
        self.SendButton.setIconSize(QtCore.QSize(32, 32))
        self.SendButton.setObjectName(_fromUtf8("SendButton"))
        self.gridLayout_7.addWidget(self.SendButton, 1, 3, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem16, 1, 2, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem17, 0, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem18, 2, 1, 1, 1)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/command-prompt-icon-1011.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseServer.addTab(self.CommandMode, icon12, _fromUtf8(""))
        self.TCPUDP_tab = QtGui.QWidget()
        self.TCPUDP_tab.setObjectName(_fromUtf8("TCPUDP_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.TCPUDP_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolBox = QtGui.QToolBox(self.TCPUDP_tab)
        self.toolBox.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 717, 282))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.page_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -176, 680, 438))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_11 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem19 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem19, 9, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem20, 0, 1, 1, 1)
        self.PortLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortLineEdit.sizePolicy().hasHeightForWidth())
        self.PortLineEdit.setSizePolicy(sizePolicy)
        self.PortLineEdit.setObjectName(_fromUtf8("PortLineEdit"))
        self.gridLayout_11.addWidget(self.PortLineEdit, 10, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_11.addWidget(self.label_4, 10, 0, 1, 1)
        self.Connect_TCPUDP = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connect_TCPUDP.sizePolicy().hasHeightForWidth())
        self.Connect_TCPUDP.setSizePolicy(sizePolicy)
        self.Connect_TCPUDP.setMinimumSize(QtCore.QSize(130, 50))
        self.Connect_TCPUDP.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.Connect_TCPUDP.setIcon(icon8)
        self.Connect_TCPUDP.setIconSize(QtCore.QSize(32, 32))
        self.Connect_TCPUDP.setObjectName(_fromUtf8("Connect_TCPUDP"))
        self.gridLayout_11.addWidget(self.Connect_TCPUDP, 13, 0, 1, 1)
        self.ServerLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerLineEdit.sizePolicy().hasHeightForWidth())
        self.ServerLineEdit.setSizePolicy(sizePolicy)
        self.ServerLineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.ServerLineEdit.setObjectName(_fromUtf8("ServerLineEdit"))
        self.gridLayout_11.addWidget(self.ServerLineEdit, 8, 1, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem21, 7, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_11.addWidget(self.label_3, 8, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem22, 11, 1, 1, 1)
        self.POP_up_checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.POP_up_checkBox.setObjectName(_fromUtf8("POP_up_checkBox"))
        self.gridLayout_11.addWidget(self.POP_up_checkBox, 14, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem23, 15, 0, 1, 1)
        self.Disconnect_TCPUDP = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disconnect_TCPUDP.sizePolicy().hasHeightForWidth())
        self.Disconnect_TCPUDP.setSizePolicy(sizePolicy)
        self.Disconnect_TCPUDP.setMinimumSize(QtCore.QSize(130, 50))
        self.Disconnect_TCPUDP.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        self.Disconnect_TCPUDP.setIcon(icon9)
        self.Disconnect_TCPUDP.setIconSize(QtCore.QSize(32, 32))
        self.Disconnect_TCPUDP.setObjectName(_fromUtf8("Disconnect_TCPUDP"))
        self.gridLayout_11.addWidget(self.Disconnect_TCPUDP, 13, 1, 1, 1, QtCore.Qt.AlignRight)
        self.SelectionCombobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectionCombobox.sizePolicy().hasHeightForWidth())
        self.SelectionCombobox.setSizePolicy(sizePolicy)
        self.SelectionCombobox.setMinimumSize(QtCore.QSize(150, 0))
        self.SelectionCombobox.setObjectName(_fromUtf8("SelectionCombobox"))
        self.SelectionCombobox.addItem(_fromUtf8(""))
        self.SelectionCombobox.addItem(_fromUtf8(""))
        self.SelectionCombobox.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.SelectionCombobox, 2, 1, 1, 1)
        self.Clear_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear_pushButton.sizePolicy().hasHeightForWidth())
        self.Clear_pushButton.setSizePolicy(sizePolicy)
        self.Clear_pushButton.setMinimumSize(QtCore.QSize(130, 50))
        self.Clear_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.Clear_pushButton.setIcon(icon2)
        self.Clear_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.Clear_pushButton.setObjectName(_fromUtf8("Clear_pushButton"))
        self.gridLayout_11.addWidget(self.Clear_pushButton, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_11.addWidget(self.label_2, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 717, 264))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.Server_IPlineEdit = QtGui.QLineEdit(self.page_4)
        self.Server_IPlineEdit.setReadOnly(True)
        self.Server_IPlineEdit.setObjectName(_fromUtf8("Server_IPlineEdit"))
        self.gridLayout_6.addWidget(self.Server_IPlineEdit, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_4)
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_4)
        self.label_7.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.Connection_lineEdit = QtGui.QLineEdit(self.page_4)
        self.Connection_lineEdit.setObjectName(_fromUtf8("Connection_lineEdit"))
        self.gridLayout_6.addWidget(self.Connection_lineEdit, 1, 2, 1, 1)
        self.Clear_pushButton_2 = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear_pushButton_2.sizePolicy().hasHeightForWidth())
        self.Clear_pushButton_2.setSizePolicy(sizePolicy)
        self.Clear_pushButton_2.setMinimumSize(QtCore.QSize(150, 50))
        self.Clear_pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.Clear_pushButton_2.setIcon(icon2)
        self.Clear_pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.Clear_pushButton_2.setObjectName(_fromUtf8("Clear_pushButton_2"))
        self.gridLayout_6.addWidget(self.Clear_pushButton_2, 0, 3, 1, 1)
        self.Server_Chat_checkBox = QtGui.QCheckBox(self.page_4)
        self.Server_Chat_checkBox.setObjectName(_fromUtf8("Server_Chat_checkBox"))
        self.gridLayout_6.addWidget(self.Server_Chat_checkBox, 4, 2, 1, 1)
        self.Server_PortlineEdit = QtGui.QLineEdit(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Server_PortlineEdit.sizePolicy().hasHeightForWidth())
        self.Server_PortlineEdit.setSizePolicy(sizePolicy)
        self.Server_PortlineEdit.setMinimumSize(QtCore.QSize(20, 0))
        self.Server_PortlineEdit.setObjectName(_fromUtf8("Server_PortlineEdit"))
        self.gridLayout_6.addWidget(self.Server_PortlineEdit, 2, 1, 1, 1)
        self.Server_pushButton = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Server_pushButton.sizePolicy().hasHeightForWidth())
        self.Server_pushButton.setSizePolicy(sizePolicy)
        self.Server_pushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.Server_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.Server_pushButton.setObjectName(_fromUtf8("Server_pushButton"))
        self.gridLayout_6.addWidget(self.Server_pushButton, 2, 2, 1, 1)
        self.ServerClose_pushButton = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerClose_pushButton.sizePolicy().hasHeightForWidth())
        self.ServerClose_pushButton.setSizePolicy(sizePolicy)
        self.ServerClose_pushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.ServerClose_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/Graphicloads-100-Flat-2-Outside.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ServerClose_pushButton.setIcon(icon13)
        self.ServerClose_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.ServerClose_pushButton.setObjectName(_fromUtf8("ServerClose_pushButton"))
        self.gridLayout_6.addWidget(self.ServerClose_pushButton, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_4)
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_4)
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 3, QtCore.Qt.AlignRight)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.toolBox, 0, 1, 1, 1)
        self.CloseServer.addTab(self.TCPUDP_tab, _fromUtf8(""))
        self.http = QtGui.QWidget()
        self.http.setObjectName(_fromUtf8("http"))
        self.gridLayout_4 = QtGui.QGridLayout(self.http)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea_3 = QtGui.QScrollArea(self.http)
        self.scrollArea_3.setStyleSheet(_fromUtf8("QScrollArea { background: transparent; }\n"
"QScrollArea > QWidget > QWidget { background: transparent; }"))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -234, 735, 533))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_12.addWidget(self.label_10, 4, 2, 1, 1)
        self.http_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_pushButton.sizePolicy().hasHeightForWidth())
        self.http_pushButton.setSizePolicy(sizePolicy)
        self.http_pushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.http_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.http_pushButton.setIcon(icon8)
        self.http_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.http_pushButton.setObjectName(_fromUtf8("http_pushButton"))
        self.gridLayout_12.addWidget(self.http_pushButton, 6, 4, 1, 1)
        self.http_getpushButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_getpushButton.sizePolicy().hasHeightForWidth())
        self.http_getpushButton.setSizePolicy(sizePolicy)
        self.http_getpushButton.setMinimumSize(QtCore.QSize(130, 50))
        self.http_getpushButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/inbox-icon-46120.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.http_getpushButton.setIcon(icon14)
        self.http_getpushButton.setIconSize(QtCore.QSize(32, 32))
        self.http_getpushButton.setObjectName(_fromUtf8("http_getpushButton"))
        self.gridLayout_12.addWidget(self.http_getpushButton, 11, 4, 1, 1)
        self.http_clearpushButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_clearpushButton.sizePolicy().hasHeightForWidth())
        self.http_clearpushButton.setSizePolicy(sizePolicy)
        self.http_clearpushButton.setMinimumSize(QtCore.QSize(130, 50))
        self.http_clearpushButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.http_clearpushButton.setIcon(icon2)
        self.http_clearpushButton.setIconSize(QtCore.QSize(32, 32))
        self.http_clearpushButton.setObjectName(_fromUtf8("http_clearpushButton"))
        self.gridLayout_12.addWidget(self.http_clearpushButton, 1, 1, 1, 1)
        self.http_close = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_close.sizePolicy().hasHeightForWidth())
        self.http_close.setSizePolicy(sizePolicy)
        self.http_close.setMinimumSize(QtCore.QSize(130, 50))
        self.http_close.setStyleSheet(_fromUtf8("background-color: rgb(139, 0, 0);"))
        self.http_close.setIcon(icon13)
        self.http_close.setIconSize(QtCore.QSize(32, 32))
        self.http_close.setObjectName(_fromUtf8("http_close"))
        self.gridLayout_12.addWidget(self.http_close, 1, 4, 1, 1, QtCore.Qt.AlignRight)
        self.http_lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_lineEdit.sizePolicy().hasHeightForWidth())
        self.http_lineEdit.setSizePolicy(sizePolicy)
        self.http_lineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.http_lineEdit.setReadOnly(False)
        self.http_lineEdit.setObjectName(_fromUtf8("http_lineEdit"))
        self.gridLayout_12.addWidget(self.http_lineEdit, 4, 4, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem24, 4, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem25, 11, 3, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem26, 4, 3, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem27, 0, 4, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem28, 1, 3, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem29, 4, 1, 1, 1)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem30, 1, 2, 1, 1)
        self.http_Send_pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_Send_pushButton.sizePolicy().hasHeightForWidth())
        self.http_Send_pushButton.setSizePolicy(sizePolicy)
        self.http_Send_pushButton.setMinimumSize(QtCore.QSize(130, 50))
        self.http_Send_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.http_Send_pushButton.setIcon(icon15)
        self.http_Send_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.http_Send_pushButton.setObjectName(_fromUtf8("http_Send_pushButton"))
        self.gridLayout_12.addWidget(self.http_Send_pushButton, 11, 2, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem31, 6, 2, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem32, 9, 5, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem33, 11, 1, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem34, 6, 0, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem35, 6, 5, 1, 1)
        spacerItem36 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem36, 6, 3, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem37, 6, 1, 1, 1)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem38, 11, 0, 1, 1)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem39, 11, 5, 1, 1)
        spacerItem40 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem40, 10, 4, 1, 1)
        spacerItem41 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem41, 8, 4, 1, 1)
        spacerItem42 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem42, 10, 2, 1, 1)
        spacerItem43 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem43, 1, 5, 1, 1)
        spacerItem44 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem44, 1, 0, 1, 1)
        spacerItem45 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem45, 5, 4, 1, 1)
        spacerItem46 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem46, 2, 4, 1, 1)
        spacerItem47 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem47, 0, 1, 1, 1)
        self.HTTPplainTextEdit = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.HTTPplainTextEdit.setObjectName(_fromUtf8("HTTPplainTextEdit"))
        self.gridLayout_12.addWidget(self.HTTPplainTextEdit, 9, 1, 1, 4)
        spacerItem48 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem48, 9, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_12.addWidget(self.lineEdit, 7, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_12.addWidget(self.label_11, 7, 2, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 1, 1, 1)
        self.CloseServer.addTab(self.http, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.CloseServer, 1, 0, 2, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.CloseServer.setCurrentIndex(4)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elementz ESP Interactive Window", None))
        self.Selection_pushButton.setText(_translate("MainWindow", "NO SELECTION", None))
        self.ConnectionStatus.setText(_translate("MainWindow", "Disconnected", None))
        self.SaveLog.setText(_translate("MainWindow", "Save Log", None))
        self.label.setText(_translate("MainWindow", "Log Window :", None))
        self.ClearLog.setText(_translate("MainWindow", "Clear Log", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))
        self.baudcomboBox.setItemText(0, _translate("MainWindow", "Select", None))
        self.baudcomboBox.setItemText(1, _translate("MainWindow", "300", None))
        self.baudcomboBox.setItemText(2, _translate("MainWindow", "600", None))
        self.baudcomboBox.setItemText(3, _translate("MainWindow", "1200", None))
        self.baudcomboBox.setItemText(4, _translate("MainWindow", "2400", None))
        self.baudcomboBox.setItemText(5, _translate("MainWindow", "4800", None))
        self.baudcomboBox.setItemText(6, _translate("MainWindow", "9600", None))
        self.baudcomboBox.setItemText(7, _translate("MainWindow", "19200", None))
        self.baudcomboBox.setItemText(8, _translate("MainWindow", "38400", None))
        self.baudcomboBox.setItemText(9, _translate("MainWindow", "57600", None))
        self.baudcomboBox.setItemText(10, _translate("MainWindow", "115200", None))
        self.findButton.setText(_translate("MainWindow", "Find Port", None))
        self.CloseServer.setTabText(self.CloseServer.indexOf(self.Settings), _translate("MainWindow", "Settings", None))
        self.Wifi_Search.setText(_translate("MainWindow", "Select  WIFI", None))
        self.WirelessSelection.setItemText(0, _translate("MainWindow", "Select", None))
        self.WirelessSelection.setItemText(1, _translate("MainWindow", "HOTSPOT", None))
        self.WirelessSelection.setItemText(2, _translate("MainWindow", "WIFI", None))
        self.WirelessSelection.setItemText(3, _translate("MainWindow", "HOTSPOT+WIFI", None))
        self.WifiCombobox.setItemText(0, _translate("MainWindow", "Select", None))
        self.wifi_pass.setPlaceholderText(_translate("MainWindow", "Password", None))
        self.checkBox.setText(_translate("MainWindow", "Show me the password", None))
        self.Default_wifi.setText(_translate("MainWindow", "Save as Default", None))
        self.wifi_connect.setText(_translate("MainWindow", "Connect", None))
        self.Disconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Select Your Mode of Connection :</p></body></html>", None))
        self.CloseServer.setTabText(self.CloseServer.indexOf(self.wireless), _translate("MainWindow", "Wireless Setup", None))
        self.SendButton.setText(_translate("MainWindow", "Execute", None))
        self.CloseServer.setTabText(self.CloseServer.indexOf(self.CommandMode), _translate("MainWindow", "Command Mode", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Port No :</p></body></html>", None))
        self.Connect_TCPUDP.setText(_translate("MainWindow", "Connect", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Server Address:</p></body></html>", None))
        self.POP_up_checkBox.setText(_translate("MainWindow", "Feeling Lonely", None))
        self.Disconnect_TCPUDP.setText(_translate("MainWindow", "Disconnect", None))
        self.SelectionCombobox.setItemText(0, _translate("MainWindow", "Select", None))
        self.SelectionCombobox.setItemText(1, _translate("MainWindow", "TCP", None))
        self.SelectionCombobox.setItemText(2, _translate("MainWindow", "UDP", None))
        self.Clear_pushButton.setText(_translate("MainWindow", "Clear Values", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">TCP or UDP:</p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "TCP/UDP Client", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Server IP :</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Connection to be Closed :</p></body></html>", None))
        self.Clear_pushButton_2.setText(_translate("MainWindow", "Clear Values", None))
        self.Server_Chat_checkBox.setText(_translate("MainWindow", "Feeling Boared", None))
        self.Server_pushButton.setText(_translate("MainWindow", " Configure Server", None))
        self.ServerClose_pushButton.setText(_translate("MainWindow", "Close Server", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Port NO :</p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Wireless Need to be Set As HOTSPOT or HOTSPOT+WIFI Mode</p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Multiple Connection TCP Server", None))
        self.CloseServer.setTabText(self.CloseServer.indexOf(self.TCPUDP_tab), _translate("MainWindow", "TCP/UDP", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Server Address</p></body></html>", None))
        self.http_pushButton.setText(_translate("MainWindow", "Connect http ", None))
        self.http_getpushButton.setText(_translate("MainWindow", "GET", None))
        self.http_clearpushButton.setText(_translate("MainWindow", "Clear", None))
        self.http_close.setText(_translate("MainWindow", "http Close", None))
        self.http_Send_pushButton.setText(_translate("MainWindow", "POST", None))
        self.HTTPplainTextEdit.setPlainText(_translate("MainWindow", "In case of GET Method Data will be shown here and in case of POST Method type \"variable=value\" in this format and put a \"&\" inbetween ", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Directory Name :</p></body></html>", None))
        self.CloseServer.setTabText(self.CloseServer.indexOf(self.http), _translate("MainWindow", "http", None))

import ESP_Resource_rc
